
-- EXERCÍCIOS


-- TOTAL VENDIDO EM CADA UM DOS MESES FILTRADO POR UM DETERMINADO ANO

-- Part1
SELECT *
	FROM TB_PEDIDO AS P
	JOIN TB_DETALHE_PEDIDO AS D
		ON P.NumeroPedido = D.NumeroPedido
	WHERE YEAR(P.DataPedido) = 1997

-- Part2
SELECT MONTH(P.DataPedido) AS MES,
		YEAR(P.DataPedido) AS ANO,
		SUM(D.Preco) AS TOTAL_VENDIDO
	FROM TB_PEDIDO AS P
	JOIN TB_DETALHE_PEDIDO AS D
		ON P.NumeroPedido = D.NumeroPedido
	WHERE YEAR(P.DataPedido) = 1997
	GROUP BY MONTH(P.DataPedido), YEAR(P.DataPedido)

-- Part3 - Criação da Procedure
CREATE PROCEDURE STP_TOTAL_VENDIDO @ANO INT
AS BEGIN
SELECT MONTH(P.DataPedido) AS MES,
		YEAR(P.DataPedido) AS ANO,
		SUM(D.Preco) AS TOTAL_VENDIDO
	FROM TB_PEDIDO AS P
	JOIN TB_DETALHE_PEDIDO AS D
		ON P.NumeroPedido = D.NumeroPedido
	WHERE YEAR(P.DataPedido) = @ANO
	GROUP BY MONTH(P.DataPedido), YEAR(P.DataPedido)
	ORDER BY 1
END

-- Part4
EXEC STP_TOTAL_VENDIDO 1999
EXEC STP_TOTAL_VENDIDO 1998
EXEC STP_TOTAL_VENDIDO 1997
EXEC STP_TOTAL_VENDIDO 1996
EXEC STP_TOTAL_VENDIDO 1999
