
-- VARIÁVEIS E OPERADORES MATEMÁTICOS

DECLARE @NUM1 INT = 10
DECLARE @NUM2 INT = 20

PRINT @NUM1 + @NUM2


DECLARE @NUM1 INT = 10, @NUM2 INT = 20, @RESULT INT

SET @RESULT = @NUM1 + @NUM2

PRINT @RESULT


-- SOMA
DECLARE @NUM1 INT = 10, @NUM2 INT = 20, @RESULT INT

SELECT @RESULT = @NUM1 + @NUM2

PRINT @RESULT

-- SUBTRAÇÃO
DECLARE @NUM1 INT = 10, @NUM2 INT = 20, @RESULT INT

SELECT @RESULT = @NUM1 - @NUM2

PRINT @RESULT

-- MULTIPLICAÇÃO
DECLARE @NUM1 INT = 10, @NUM2 INT = 20, @RESULT INT

SELECT @RESULT = @NUM1 * @NUM2

PRINT @RESULT

-- DIVISÃO
DECLARE @NUM1 INT = 10, @NUM2 INT = 20, @RESULT INT

SELECT @RESULT = @NUM1 / @NUM2

PRINT @RESULT

-- RESTO DA DIVISÃO
DECLARE @NUM1 INT = 10, @NUM2 INT = 20, @RESULT INT

SELECT @RESULT = @NUM1 % @NUM2

PRINT @RESULT
