
-- CONTROLE DE FLUXO 2

IF OBJECT_ID('TB_TESTE_NOVO', 'U') IS NULL
CREATE TABLE TB_TESTE_NOVO (ID VARCHAR(15))
 

 IF OBJECT_ID('TB_TESTE_NOVO', 'U') IS NOT NULL
 DROP TABLE TB_TESTE_NOVO;

CREATE TABLE TB_TESTE_NOVO (ID VARCHAR(15))
