
-- LISTA TODOS CLIENTES QUE MORAM NA ALEMANHA

SELECT C.NomeCompleto, E.Pais FROM TB_CLIENTE AS C
JOIN TB_ENDERECO AS E ON C.ClienteId = E.ClienteId
WHERE E.Pais = 'Alemanha'

-- LISTA TODOS CLIENTES QUE COMPRARAM PRODUTOS DA CATEGORIA BEBIDA

SELECT C.NomeCompleto, CA.Descricao FROM TB_CLIENTE AS C
JOIN TB_PEDIDO AS P ON C.ClienteId = P.ClienteId
JOIN TB_DETALHE_PEDIDO AS D ON P.NumeroPedido = D.NumeroPedido
JOIN TB_PRODUTO AS PR ON D.ProdutoId = PR.ProdutoId
JOIN TB_CATEGORIA AS CA ON PR.CategoriaId = CA.CategoriaId
WHERE CA.Descricao = 'Bebidas'
