
-- ALTER VIEW

ALTER VIEW VIE_PED2
WITH ENCRYPTION
AS
SELECT  F.NomeCompleto,
		P.NumeroPedido,
		P.DataPedido
FROM dbo.TB_FUNCIONARIO AS F
JOIN dbo.TB_PEDIDO AS P
	ON F.FuncionarioId = P.FuncionarioId

ALTER TABLE TB_FUNCIONARIO
DROP COLUMN TESTE

SELECT * FROM TB_FUNCIONARIO
SELECT * FROM VIE_PED2