
CREATE TABLE TB_PRODUTO
(
	ProdutoId INT IDENTITY (1, 1) PRIMARY KEY NOT NULL,
	ProdutoId_2 INT IDENTITY (1, 1),
	
	NumContrato INT, 

	CONSTRAINT PK_PRODUTO PRIMARY KEY (ProdutoId_2, NumContrato)
)

ALTER TABLE TB_PRODUTO
ADD CONSTRAINT PK_PRODUTO PRIMARY KEY(ProdutoId);

CREATE TABLE TB_CLIENTE
(
	CPF VARCHAR (12) NOT NULL,
	CONSTRAINT UQ_CLIENTE_CPF UNIQUE(CPF)
)

ALTER TABLE TB_CLIENTE
ADD CONSTRAINT UQ_CLIENTE_CPF UNIQUE(CPF);