CREATE TABLE TB_CLIENTE
(
	Idade INT NOT NULL,
	DataCriacao DATETIME2 NOT NULL DEFAULT GETDATE(),
	CONSTRAINT CK_CLIENTE_IDADE CHECK(Idade > 16)
);

ALTER TABLE TB_CLIENTE
ADD CONSTRAINT CK_CLIENTE_IDADE CHECK (Idade > 16)

ALTER TABLE TB_CLIENTE
ADD CONSTRAINT DF_CLIENTE_DATACRIACAO DEFAULT (GETDATE()) FOR DataCriacao
