
SELECT * FROM TB_ENDERECO
WHERE Pais IN('EUA', 'Suécia', 'França')

SELECT * FROM TB_ENDERECO
WHERE Pais NOT IN('EUA', 'Suécia', 'França')

SELECT * FROM TB_ENDERECO
WHERE Regiao IS NULL

SELECT * FROM TB_ENDERECO
WHERE Regiao IS NOT NULL

SELECT Logradouro, Cidade, Pais, ISNULL(Regiao, 'N/C') FROM TB_ENDERECO
WHERE Regiao IS NULL