
SELECT * FROM TB_DETALHE_PEDIDO

-- Máximo
SELECT MAX(PRECO) FROM TB_DETALHE_PEDIDO
WHERE NumeroPedido = 10248

-- Mínimo
SELECT MIN(PRECO) FROM TB_DETALHE_PEDIDO
WHERE NumeroPedido = 10248

-- Média
SELECT NumeroPedido, AVG(PRECO) FROM TB_DETALHE_PEDIDO
GROUP BY NumeroPedido

-- Soma
SELECT NumeroPedido, SUM(PRECO) FROM TB_DETALHE_PEDIDO
GROUP BY NumeroPedido

-- Contar
SELECT NumeroPedido, COUNT(*) FROM TB_DETALHE_PEDIDO
GROUP BY NumeroPedido


SELECT NumeroPedido, MAX(Preco) FROM TB_DETALHE_PEDIDO
GROUP BY NumeroPedido

SELECT NumeroPedido, MIN(Preco) FROM TB_DETALHE_PEDIDO
GROUP BY NumeroPedido