
-- TRIGGER DML - Exercicio 01


-- Part1
CREATE TABLE TB_HIST_SALARIO
(
	FuncionarioId INT PRIMARY KEY,
	DATA_ALTERACAO DATETIME2 DEFAULT GETDATE(),
	SALARIO_ANTIGO MONEY,
	SALARIO_NOVO MONEY,
	CONSTRAINT FK_TB_HIST_SALARIO_FUNCIONARIO FOREIGN KEY (FuncionarioId)
	REFERENCES TB_Funcionario(FuncionarioId)
);

SELECT * FROM TB_HIST_SALARIO


-- Part2 - Criação do Trigger
CREATE TRIGGER TRG_FUNCIONARIOS_HIST_SALARIO ON TB_FUNCIONARIO
FOR UPDATE
AS BEGIN
	DECLARE @FUNCIONARIO_ID INT, @SALARIO_ANTIGO MONEY, @SALARIO_NOVO MONEY;

	SELECT @SALARIO_ANTIGO = Salario FROM deleted;

	SELECT @FUNCIONARIO_ID = FuncionarioId, @SALARIO_NOVO = Salario FROM inserted;

	IF @SALARIO_ANTIGO <> @SALARIO_NOVO
	BEGIN
		INSERT INTO TB_HIST_SALARIO
		(FuncionarioId, SALARIO_ANTIGO, SALARIO_NOVO)
		VALUES
		(@FUNCIONARIO_ID, @SALARIO_ANTIGO, @SALARIO_NOVO)
	END
END


-- Part3
SELECT * FROM TB_FUNCIONARIO

UPDATE TB_FUNCIONARIO
SET Salario = 6500.00
WHERE FuncionarioId = 1

SELECT * FROM TB_HIST_SALARIO
