
-- TRIGGER DML - Exercicio 02


-- Part1
SELECT * FROM TB_PEDIDO

ALTER TABLE TB_PEDIDO
ADD VALOR_TOTAL MONEY DEFAULT 0

SELECT * FROM TB_PEDIDO


-- Part 2 -- Criação do Trigger
CREATE TRIGGER TRG_CORRIGE_VLR_TOTAL ON TB_DETALHE_PEDIDO
FOR DELETE, INSERT, UPDATE
AS BEGIN
	-- PARA EVENTO DE DELETE
	IF NOT EXISTS(SELECT * FROM inserted)
	BEGIN
		UPDATE TB_PEDIDO
		SET VALOR_TOTAL = (SELECT SUM(D.Preco * D.Quantidade) FROM TB_DETALHE_PEDIDO AS D
							WHERE P.NumeroPedido = D.NumeroPedido)
							FROM TB_PEDIDO AS P JOIN deleted
							ON P.NumeroPedido = deleted.NumeroPedido;
	END
	-- PARA EVENTO DE UPDATE OU INSERT
	ELSE
	BEGIN
		UPDATE TB_PEDIDO
		SET VALOR_TOTAL = (SELECT SUM(D.Preco * D.Quantidade) FROM TB_DETALHE_PEDIDO AS D
							WHERE P.NumeroPedido = D.NumeroPedido)
							FROM TB_PEDIDO AS P JOIN inserted
							ON P.NumeroPedido = inserted.NumeroPedido;
	END
END


-- Part3
SELECT * FROM TB_PEDIDO

SELECT * FROM TB_PEDIDO WHERE NumeroPedido = 10249

SELECT * FROM TB_DETALHE_PEDIDO WHERE NumeroPedido = 10249

UPDATE TB_DETALHE_PEDIDO
SET Quantidade = 10
WHERE NumeroPedido = 10249 AND ProdutoId = 14

SELECT * FROM TB_PEDIDO WHERE NumeroPedido = 10249

SELECT * FROM TB_DETALHE_PEDIDO WHERE NumeroPedido = 10249
