
-- TRIGGER DML - Exercicio 03


-- Part1
SELECT * FROM TB_CLIENTE

ALTER TABLE TB_CLIENTE
ADD Ativo BIT DEFAULT 1

SELECT * FROM TB_CLIENTE

UPDATE TB_CLIENTE
SET Ativo = 1

SELECT * FROM TB_CLIENTE


-- Part2 - Criação do Trigger
CREATE TRIGGER TRG_DESATIVA_CLIENTE ON TB_CLIENTE
INSTEAD OF DELETE
AS BEGIN
	UPDATE TB_CLIENTE SET Ativo = 0
	FROM TB_CLIENTE AS C JOIN deleted AS D ON C.ClienteId = D.ClienteId
END


-- Part3
SELECT * FROM TB_CLIENTE

DELETE TB_CLIENTE
WHERE ClienteId = 'ALFKI'

SELECT * FROM TB_CLIENTE
WHERE ClienteId = 'ALFKI'
