
SELECT  C2.NomeCompleto,
		C2.Cargo,
		C2.ANO_MES,
		C2.SOMATORIA_QUANTIDADE,
		C2.SOMATORIA_PRECO,
		C2.VALOR_TOTAL,
		CASE
			WHEN C2.VALOR_TOTAL >= 5000
				THEN 'BATEU A META'
			ELSE
				'NÃO BATEU A META'
		END AS [STATUS]
FROM
	(SELECT  CLI.NomeCompleto,
			CLI.Cargo,
			C1.ANO_MES,
			C1.SOMATORIA_QUANTIDADE,
			C1.SOMATORIA_PRECO,
			C1.VALOR_TOTAL
	FROM
	(SELECT	P.ClienteId, 
			SUBSTRING(CONVERT(VARCHAR, P.DataPedido, 120), 1, 7) AS ANO_MES, 
			SUM(D.Quantidade) SOMATORIA_QUANTIDADE, 
			SUM(D.Preco) SOMATORIA_PRECO, 
			SUM(D.Quantidade) * SUM(D.Preco) VALOR_TOTAL
			FROM TB_DETALHE_PEDIDO AS D
	JOIN TB_PEDIDO AS P ON D.NumeroPedido = P.NumeroPedido
	GROUP BY P.ClienteId, SUBSTRING(CONVERT(VARCHAR, P.DataPedido, 120), 1, 7)) AS C1
	JOIN TB_CLIENTE AS CLI ON C1.ClienteId = CLI.ClienteId) AS C2