
SELECT  C1.CATEGORIA,
		C1.ANO,
		CONVERT(DECIMAL(15, 2), C1.FATURAMENTO) AS FATURAMENTO,
		(C1.FATURAMENTO/C2.FATURAMENTO) * 100 [PERCENTUAL (%)]

FROM
	(SELECT  CA.Descricao CATEGORIA,
			YEAR(PE.DataPedido) AS ANO,
			SUM(DE.Quantidade * DE.Preco) AS FATURAMENTO
		FROM TB_DETALHE_PEDIDO AS DE
		JOIN TB_PRODUTO AS PR
			ON DE.ProdutoId = PR.ProdutoId
		JOIN TB_CATEGORIA AS CA
			ON CA.CategoriaId = PR.CategoriaId
		JOIN TB_PEDIDO AS PE
			ON PE.NumeroPedido = DE.NumeroPedido
		WHERE YEAR(PE.DataPedido) = 1996
		GROUP BY CA.Descricao, YEAR(PE.DataPedido)) AS C1
	INNER JOIN
	(SELECT	YEAR(PE.DataPedido) AS ANO,
			SUM(DE.Quantidade * DE.Preco) AS FATURAMENTO
		FROM TB_DETALHE_PEDIDO AS DE
		JOIN TB_PRODUTO AS PR
			ON DE.ProdutoId = PR.ProdutoId
		JOIN TB_CATEGORIA AS CA
			ON CA.CategoriaId = PR.CategoriaId
		JOIN TB_PEDIDO AS PE
			ON PE.NumeroPedido = DE.NumeroPedido
		WHERE YEAR(PE.DataPedido) = 1996
		GROUP BY YEAR(PE.DataPedido)) AS C2
	ON C1.ANO = C2.ANO
	ORDER BY C1.FATURAMENTO DESC